### ISSUE TITLE
tts python api 第二次调用还是加载了模型

### ISSUE THREAD

**Issue by yt605155624** [phecda-xu/PaddleDubbing#2]
具体可以参考如下链接修改

https://github.com/PaddlePaddle/PaddleSpeech/issues/1455

**Comment by phecda-xu** [comment]
> 具体可以参考如下链接修改
> 
> [PaddlePaddle/PaddleSpeech#1455](https://github.com/PaddlePaddle/PaddleSpeech/issues/1455)

谢谢，已修改。
