### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/PaddleDubbing/models/other/pitch_stats.npy'

### ISSUE THREAD

**Issue by zhoujian1028** [phecda-xu/PaddleDubbing#3]
你好，
![image](https://user-images.githubusercontent.com/6960679/207013869-02aee6af-1503-4c93-9709-228ff06d13e9.png)
相关模型已下载到models目录 执行为啥还报错 谢谢
FileNotFoundError: [Errno 2] No such file or directory: '/data/PaddleDubbing/models/other/pitch_stats.npy'

**Comment by phecda-xu** [comment]
不好意思啊，变速变调用的两个文件忘记上传了，已经补全。
